#pragma once
#include <Geode/Geode.hpp>

struct checkpoint_data {
    uint64_t currentFrame;
    // cocos2d::CCNode* m_mainLayer;
    bool m_wasTeleported;
    bool m_fixGravityBug;
    bool m_reverseSync;
    double m_yVelocityBeforeSlope;
    double m_dashX;
    double m_dashY;
    double m_dashAngle;
    double m_dashStartTime;
    // DashRingObject* m_dashRing;
    double m_slopeStartTime;
    bool m_justPlacedStreak;
    // GameObject* m_maybeLastGroundObject;
    // cocos2d::CCDictionary* m_collisionLogTop;
    // cocos2d::CCDictionary* m_collisionLogBottom;
    // cocos2d::CCDictionary* m_collisionLogLeft;
    // cocos2d::CCDictionary* m_collisionLogRight;
    int m_lastCollisionBottom;
    int m_lastCollisionTop;
    int m_lastCollisionLeft;
    int m_lastCollisionRight;
    int m_unk50C;
    int m_unk510;
    GameObject* m_currentSlope2;
    GameObject* m_preLastGroundObject;
    float m_slopeAngle;
    bool m_slopeSlidingMaybeRotated;
    bool m_quickCheckpointMode;
    GameObject* m_collidedObject;
    GameObject* m_lastGroundObject;
    GameObject* m_collidingWithLeft;
    GameObject* m_collidingWithRight;
    int m_maybeSavedPlayerFrame;
    double m_scaleXRelated2;
    double m_groundYVelocity;
    double m_yVelocityRelated;
    double m_scaleXRelated3;
    // bool m_collidingBetweenSteps;
    double m_scaleXRelated4;
    double m_scaleXRelated5;
    bool m_isCollidingWithSlope;
    // cocos2d::CCSprite* m_dashFireSprite;
    bool m_isBallRotating;
    bool m_unk669;
    GameObject* m_currentPotentialSlope;
    GameObject* m_currentSlope;
    double unk_584;
    int m_collidingWithSlopeId;
    bool m_slopeFlipGravityRelated;
    // cocos2d::CCArray* m_particleSystems;
    float m_slopeAngleRadians;
    float m_rotationSpeed;
    float m_rotateSpeed;
    bool m_isRotating;
    bool m_isBallRotating2;
    // bool m_hasGlow;
    bool m_isHidden;
    // GhostType m_ghostType;
    // GhostTrailEffect* m_ghostTrail;
    // cocos2d::CCSprite* m_iconSprite;
    // cocos2d::CCSprite* m_iconSpriteSecondary;
    // cocos2d::CCSprite* m_iconSpriteWhitener;
    // cocos2d::CCSprite* m_iconGlow;
    // cocos2d::CCSprite* m_vehicleSprite;
    // cocos2d::CCSprite* m_vehicleSpriteSecondary;
    // cocos2d::CCSprite* m_birdVehicle;
    // cocos2d::CCSprite* m_vehicleSpriteWhitener;
    // cocos2d::CCSprite* m_vehicleGlow;
    // PlayerFireBoostSprite* m_swingFireMiddle;
    // PlayerFireBoostSprite* m_swingFireBottom;
    // PlayerFireBoostSprite* m_swingFireTop;
    // cocos2d::CCSprite* m_dashSpritesContainer;
    // cocos2d::CCMotionStreak* m_regularTrail;
    // cocos2d::CCMotionStreak* m_shipStreak;

    // HardStreak* m_waveTrail;
    std::vector<cocos2d::CCPoint> m_waveTrailPoints;

    double m_speedMultiplier;
    double m_yStart;
    double m_gravity;
    float m_trailingParticleLife;
    float m_unk648;
    double m_gameModeChangedTime;
    bool m_padRingRelated;
    bool m_maybeReducedEffects;
    bool m_maybeIsFalling;
    bool m_shouldTryPlacingCheckpoint;
    bool m_playEffects;
    bool m_maybeCanRunIntoBlocks;
    bool m_hasGroundParticles;
    bool m_hasShipParticles;
    bool m_isOnGround3;
    bool m_checkpointTimeout;
    double m_lastCheckpointTime;
    double m_lastJumpTime;
    double m_lastFlipTime;
    double m_flashTime;
    float m_flashDuration;
    float m_flashDelay;
    cocos2d::ccColor3B m_flashMainColor;
    cocos2d::ccColor3B m_flashSecondColor;
    double m_lastSpiderFlipTime;
    bool m_unkBool5;
    bool m_maybeIsVehicleGlowing;
    // bool m_switchWaveTrailColor;
    // bool m_practiceDeathEffect;
    double m_accelerationOrSpeed;
    double m_snapDistance;
    bool m_ringJumpRelated;
    GameObject* m_objectSnappedTo;
    // CheckpointObject* m_pendingCheckpoint;
    int m_onFlyCheckpointTries;
    // GJRobotSprite* m_robotSprite;
    // GJSpiderSprite* m_spiderSprite;
    bool m_maybeSpriteRelated;
    // cocos2d::CCParticleSystemQuad* m_playerGroundParticles;
    // cocos2d::CCParticleSystemQuad* m_trailingParticles;
    // cocos2d::CCParticleSystemQuad* m_shipClickParticles;
    // cocos2d::CCParticleSystemQuad* m_vehicleGroundParticles;
    // cocos2d::CCParticleSystemQuad* m_ufoClickParticles;
    // cocos2d::CCParticleSystemQuad* m_robotBurstParticles;
    // cocos2d::CCParticleSystemQuad* m_dashParticles;
    // cocos2d::CCParticleSystemQuad* m_swingBurstParticles1;
    // cocos2d::CCParticleSystemQuad* m_swingBurstParticles2;
    bool m_useLandParticles0;
    // cocos2d::CCParticleSystemQuad* m_landParticles0;
    // cocos2d::CCParticleSystemQuad* m_landParticles1;
    float m_landParticlesAngle;
    float m_landParticleRelatedY;
    int m_playerStreak;
    float m_streakStrokeWidth;
    bool m_disableStreakTint;
    bool m_alwaysShowStreak;
    ShipStreak m_shipStreakType;
    double m_slopeRotation;
    double m_currentSlopeYVelocity;
    double m_unk3d0;
    double m_blackOrbRelated;
    bool m_unk3e0;
    bool m_unk3e1;
    bool m_isAccelerating;
    bool m_isCurrentSlopeTop;
    double m_collidedTopMinY;
    double m_collidedBottomMaxY;
    double m_collidedLeftMaxX;
    double m_collidedRightMinX;
    bool m_fadeOutStreak;
    bool m_canPlaceCheckpoint;
    cocos2d::ccColor3B m_originalMainColor;
    cocos2d::ccColor3B m_originalSecondColor;
    // bool m_hasCustomGlowColor;
    // cocos2d::ccColor3B m_glowColor;
    bool m_maybeIsColliding;
    bool m_jumpBuffered;
    bool m_stateRingJump;
    bool m_wasJumpBuffered;
    bool m_wasRobotJump;
    unsigned char m_stateJumpBuffered;
    bool m_stateRingJump2;
    bool m_touchedRing;
    bool m_touchedCustomRing;
    bool m_touchedGravityPortal;
    bool m_maybeTouchedBreakableBlock;
    geode::SeedValueRSV m_jumpRelatedAC2;
    bool m_touchedPad;
    double m_yVelocity;
    double m_fallSpeed;
    bool m_isOnSlope;
    bool m_wasOnSlope;
    float m_slopeVelocity;
    bool m_maybeUpsideDownSlope;
    bool m_isShip;
    bool m_isBird;
    bool m_isBall;
    bool m_isDart;
    bool m_isRobot;
    bool m_isSpider;
    bool m_isUpsideDown;
    bool m_isDead;
    bool m_isOnGround;
    bool m_isGoingLeft;
    bool m_isSideways;
    bool m_isSwing;
    int m_reverseRelated;
    double m_maybeReverseSpeed;
    double m_maybeReverseAcceleration;
    float m_xVelocityRelated2;
    bool m_isDashing;
    int m_dashFireFrame;
    int m_groundObjectMaterial;
    float m_vehicleSize;
    float m_playerSpeed;
    cocos2d::CCPoint m_shipRotation;
    cocos2d::CCPoint m_lastPortalPos;
    float m_unkUnused3;
    bool m_isOnGround2;
    double m_lastLandTime;
    float m_platformerVelocityRelated;
    bool m_maybeIsBoosted;
    double m_scaleXRelatedTime;
    bool m_decreaseBoostSlide;
    bool m_unkA29;
    bool m_isLocked;
    bool m_controlsDisabled;
    cocos2d::CCPoint m_lastGroundedPos;
    GameObject* m_lastActivatedPortal;
    bool m_hasEverJumped;
    bool m_hasEverHitRing;
    cocos2d::ccColor3B m_playerColor1;
    cocos2d::ccColor3B m_playerColor2;
    cocos2d::CCPoint m_position;
    float m_rotation;
    bool m_isSecondPlayer;
    bool m_unkA99;
    double m_totalTime;
    bool m_isBeingSpawnedByDualPortal;
    float m_audioScale;
    float m_unkAngle1;
    float m_yVelocityRelated3;
    bool m_defaultMiniIcon;
    bool m_swapColors;
    bool m_switchDashFireColor;
    int m_followRelated;
    float m_unk838;
    int m_stateOnGround;
    unsigned char m_stateUnk;
    unsigned char m_stateNoStickX;
    unsigned char m_stateNoStickY;
    unsigned char m_stateUnk2;
    int m_stateBoostX;
    int m_stateBoostY;
    int m_maybeStateForce2;
    int m_stateScale;
    double m_platformerXVelocity;
    bool m_holdingRight;
    bool m_holdingLeft;
    bool m_leftPressedFirst;
    double m_scaleXRelated;
    bool m_maybeHasStopped;
    float m_xVelocityRelated;
    bool m_maybeGoingCorrectSlopeDirection;
    bool m_isSliding;
    double m_maybeSlopeForce;
    bool m_isOnIce;
    double m_physDeltaRelated;
    bool m_isOnGround4;
    int m_maybeSlidingTime;
    double m_maybeSlidingStartTime;
    double m_changedDirectionsTime;
    double m_slopeEndTime;
    bool m_isMoving;
    bool m_platformerMovingLeft;
    bool m_platformerMovingRight;
    bool m_isSlidingRight;
    double m_maybeChangedDirectionAngle;
    double m_unkUnused2;
    bool m_isPlatformer;
    int m_stateNoAutoJump;
    int m_stateDartSlide;
    int m_stateHitHead;
    int m_stateFlipGravity;
    float m_gravityMod;
    int m_stateForce;
    cocos2d::CCPoint m_stateForceVector;
    bool m_affectedByForces;
    float m_somethingPlayerSpeedTime;
    float m_playerSpeedAC;
    bool m_fixRobotJump;
    // gd::map<int, bool> m_holdingButtons;
    bool m_inputsLocked;
    bool m_gv0123;
    int m_iconRequestID;
    // cocos2d::CCSpriteBatchNode* m_robotBatchNode;
    // cocos2d::CCSpriteBatchNode* m_spiderBatchNode;
    // cocos2d::CCArray* m_unk958;
    // PlayerFireBoostSprite* m_robotFire;
    int m_unkUnused;
    // GJBaseGameLayer* m_gameLayer;
    // cocos2d::CCLayer* m_parentLayer;
    // GJActionManager* m_actionManager;
    bool m_isOutOfBounds;
    float m_fallStartY;
    bool m_disablePlayerSqueeze;
    bool m_robotAnimation1Enabled;
    bool m_robotAnimation2Enabled;
    bool m_spiderAnimationEnabled;
    bool m_ignoreDamage;
    bool m_enable22Changes;

    std::array<bool, 3> m_clickReleased;

    // gd::unordered_map<int, GJPointDouble> m_rotateObjectsRelated; // breaking
    // gd::unordered_map<int, GameObject*> m_potentialSlopeMap; // breaking
    // gd::unordered_set<int> m_ringRelatedSet; // breaking
	
	// cocos2d::CCArray* m_touchingRings; // original array
    // gd::vector<cocos2d::CCObject*> m_touchingRings; // breaking

    // gd::unordered_set<int> m_touchedRings; // breaking
    // gd::vector<float> m_playerFollowFloats; // breaking
    // gd::map<int, bool> m_jumpPadRelated; // breaking
    // gd::string m_currentRobotAnimation; // breaking
};

namespace GDH { namespace PracticeFix {
    inline checkpoint_data store(PlayerObject* player, std::array<bool, 3>& releasedClicks, const int64_t& currentFrame) {
        checkpoint_data state;
        if (player == nullptr) return state;

        state.currentFrame = currentFrame;

        // state.m_mainLayer = player->m_mainLayer;
        state.m_wasTeleported = player->m_wasTeleported;
        state.m_fixGravityBug = player->m_fixGravityBug;
        state.m_reverseSync = player->m_reverseSync;
        state.m_yVelocityBeforeSlope = player->m_yVelocityBeforeSlope;
        state.m_dashX = player->m_dashX;
        state.m_dashY = player->m_dashY;
        state.m_dashAngle = player->m_dashAngle;
        state.m_dashStartTime = player->m_dashStartTime;
        // state.m_dashRing = player->m_dashRing;
        state.m_slopeStartTime = player->m_slopeStartTime;
        state.m_justPlacedStreak = player->m_justPlacedStreak;
        // state.m_maybeLastGroundObject = player->m_maybeLastGroundObject;
        // state.m_collisionLogTop = player->m_collisionLogTop;
        // state.m_collisionLogBottom = player->m_collisionLogBottom;
        // state.m_collisionLogLeft = player->m_collisionLogLeft;
        // state.m_collisionLogRight = player->m_collisionLogRight;
        state.m_lastCollisionBottom = player->m_lastCollisionBottom;
        state.m_lastCollisionTop = player->m_lastCollisionTop;
        state.m_lastCollisionLeft = player->m_lastCollisionLeft;
        state.m_lastCollisionRight = player->m_lastCollisionRight;
        state.m_unk50C = player->m_unk50C;
        state.m_unk510 = player->m_unk510;
        state.m_currentSlope2 = player->m_currentSlope2;
        state.m_preLastGroundObject = player->m_preLastGroundObject;
        state.m_slopeAngle = player->m_slopeAngle;
        state.m_slopeSlidingMaybeRotated = player->m_slopeSlidingMaybeRotated;
        state.m_quickCheckpointMode = player->m_quickCheckpointMode;
        state.m_collidedObject = player->m_collidedObject;
        state.m_lastGroundObject = player->m_lastGroundObject;
        state.m_collidingWithLeft = player->m_collidingWithLeft;
        state.m_collidingWithRight = player->m_collidingWithRight;
        state.m_maybeSavedPlayerFrame = player->m_maybeSavedPlayerFrame;
        state.m_scaleXRelated2 = player->m_scaleXRelated2;
        state.m_groundYVelocity = player->m_groundYVelocity;
        state.m_yVelocityRelated = player->m_yVelocityRelated;
        state.m_scaleXRelated3 = player->m_scaleXRelated3;

        // #if defined(GEODE_IS_ANDROID) || defined(GEODE_IS_IOS)
        // state.m_collidingBetweenSteps = player->m_collidingBetweenSteps;
        // #else
        // state.m_collidingBetweenSteps = false;
        // #endif

        state.m_scaleXRelated4 = player->m_scaleXRelated4;
        state.m_scaleXRelated5 = player->m_scaleXRelated5;
        state.m_isCollidingWithSlope = player->m_isCollidingWithSlope;
        // state.m_dashFireSprite = player->m_dashFireSprite;
        state.m_isBallRotating = player->m_isBallRotating;
        state.m_unk669 = player->m_unk669;
        state.m_currentPotentialSlope = player->m_currentPotentialSlope;
        state.m_currentSlope = player->m_currentSlope;
        state.unk_584 = player->unk_584;
        state.m_collidingWithSlopeId = player->m_collidingWithSlopeId;
        state.m_slopeFlipGravityRelated = player->m_slopeFlipGravityRelated;
        // state.m_particleSystems = player->m_particleSystems;
        state.m_slopeAngleRadians = player->m_slopeAngleRadians;
        state.m_rotationSpeed = player->m_rotationSpeed;
        state.m_rotateSpeed = player->m_rotateSpeed;
        state.m_isRotating = player->m_isRotating;
        state.m_isBallRotating2 = player->m_isBallRotating2;
        // state.m_hasGlow = player->m_hasGlow;
        state.m_isHidden = player->m_isHidden;
        // state.m_ghostType = player->m_ghostType;
        // state.m_ghostTrail = player->m_ghostTrail;
        // state.m_iconSprite = player->m_iconSprite;
        // state.m_iconSpriteSecondary = player->m_iconSpriteSecondary;
        // state.m_iconSpriteWhitener = player->m_iconSpriteWhitener;
        // state.m_iconGlow = player->m_iconGlow;
        // state.m_vehicleSprite = player->m_vehicleSprite;
        // state.m_vehicleSpriteSecondary = player->m_vehicleSpriteSecondary;
        // state.m_birdVehicle = player->m_birdVehicle;
        // state.m_vehicleSpriteWhitener = player->m_vehicleSpriteWhitener;
        // state.m_vehicleGlow = player->m_vehicleGlow;
        // state.m_swingFireMiddle = player->m_swingFireMiddle;
        // state.m_swingFireBottom = player->m_swingFireBottom;
        // state.m_swingFireTop = player->m_swingFireTop;
        // state.m_dashSpritesContainer = player->m_dashSpritesContainer;
        // state.m_regularTrail = player->m_regularTrail;
        // state.m_shipStreak = player->m_shipStreak;
        
        // state.m_waveTrail = player->m_waveTrail;
        if (player && player->m_waveTrail && player->m_waveTrail->m_pointArray) {
            auto points = player->m_waveTrail->m_pointArray;
            
            for (int i = 0; i < points->count(); i++) {
                if (auto node = static_cast<PointNode*>(points->objectAtIndex(i))) {
                    state.m_waveTrailPoints.push_back(node->m_point);
                }
            }
        }
        
        state.m_speedMultiplier = player->m_speedMultiplier;
        state.m_yStart = player->m_yStart;
        state.m_gravity = player->m_gravity;
        state.m_trailingParticleLife = player->m_trailingParticleLife;
        state.m_unk648 = player->m_unk648;
        state.m_gameModeChangedTime = player->m_gameModeChangedTime;
        state.m_padRingRelated = player->m_padRingRelated;
        state.m_maybeReducedEffects = player->m_maybeReducedEffects;
        state.m_maybeIsFalling = player->m_maybeIsFalling;
        state.m_shouldTryPlacingCheckpoint = player->m_shouldTryPlacingCheckpoint;
        state.m_playEffects = player->m_playEffects;
        state.m_maybeCanRunIntoBlocks = player->m_maybeCanRunIntoBlocks;
        state.m_hasGroundParticles = player->m_hasGroundParticles;
        state.m_hasShipParticles = player->m_hasShipParticles;
        state.m_isOnGround3 = player->m_isOnGround3;
        state.m_checkpointTimeout = player->m_checkpointTimeout;
        state.m_lastCheckpointTime = player->m_lastCheckpointTime;
        state.m_lastJumpTime = player->m_lastJumpTime;
        state.m_lastFlipTime = player->m_lastFlipTime;
        state.m_flashTime = player->m_flashTime;
        state.m_flashDuration = player->m_flashDuration;
        state.m_flashDelay = player->m_flashDelay;
        state.m_flashMainColor = player->m_flashMainColor;
        state.m_flashSecondColor = player->m_flashSecondColor;
        state.m_lastSpiderFlipTime = player->m_lastSpiderFlipTime;
        state.m_unkBool5 = player->m_unkBool5;
        state.m_maybeIsVehicleGlowing = player->m_maybeIsVehicleGlowing;
        // state.m_switchWaveTrailColor = player->m_switchWaveTrailColor;
        // state.m_practiceDeathEffect = player->m_practiceDeathEffect;
        state.m_accelerationOrSpeed = player->m_accelerationOrSpeed;
        state.m_snapDistance = player->m_snapDistance;
        state.m_ringJumpRelated = player->m_ringJumpRelated;
        state.m_objectSnappedTo = player->m_objectSnappedTo;
        // state.m_pendingCheckpoint = player->m_pendingCheckpoint;
        state.m_onFlyCheckpointTries = player->m_onFlyCheckpointTries;
        // state.m_robotSprite = player->m_robotSprite;
        // state.m_spiderSprite = player->m_spiderSprite;
        state.m_maybeSpriteRelated = player->m_maybeSpriteRelated;
        // state.m_playerGroundParticles = player->m_playerGroundParticles;
        // state.m_trailingParticles = player->m_trailingParticles;
        // state.m_shipClickParticles = player->m_shipClickParticles;
        // state.m_vehicleGroundParticles = player->m_vehicleGroundParticles;
        // state.m_ufoClickParticles = player->m_ufoClickParticles;
        // state.m_robotBurstParticles = player->m_robotBurstParticles;
        // state.m_dashParticles = player->m_dashParticles;
        // state.m_swingBurstParticles1 = player->m_swingBurstParticles1;
        // state.m_swingBurstParticles2 = player->m_swingBurstParticles2;
        state.m_useLandParticles0 = player->m_useLandParticles0;
        // state.m_landParticles0 = player->m_landParticles0;
        // state.m_landParticles1 = player->m_landParticles1;
        state.m_landParticlesAngle = player->m_landParticlesAngle;
        state.m_landParticleRelatedY = player->m_landParticleRelatedY;
        state.m_playerStreak = player->m_playerStreak;
        state.m_streakStrokeWidth = player->m_streakStrokeWidth;
        state.m_disableStreakTint = player->m_disableStreakTint;
        state.m_alwaysShowStreak = player->m_alwaysShowStreak;
        state.m_shipStreakType = player->m_shipStreakType;
        state.m_slopeRotation = player->m_slopeRotation;
        state.m_currentSlopeYVelocity = player->m_currentSlopeYVelocity;
        state.m_unk3d0 = player->m_unk3d0;
        state.m_blackOrbRelated = player->m_blackOrbRelated;
        state.m_unk3e0 = player->m_unk3e0;
        state.m_unk3e1 = player->m_unk3e1;
        state.m_isAccelerating = player->m_isAccelerating;
        state.m_isCurrentSlopeTop = player->m_isCurrentSlopeTop;
        state.m_collidedTopMinY = player->m_collidedTopMinY;
        state.m_collidedBottomMaxY = player->m_collidedBottomMaxY;
        state.m_collidedLeftMaxX = player->m_collidedLeftMaxX;
        state.m_collidedRightMinX = player->m_collidedRightMinX;
        state.m_fadeOutStreak = player->m_fadeOutStreak;
        state.m_canPlaceCheckpoint = player->m_canPlaceCheckpoint;
        state.m_originalMainColor = player->m_originalMainColor;
        state.m_originalSecondColor = player->m_originalSecondColor;
        // state.m_hasCustomGlowColor = player->m_hasCustomGlowColor;
        // state.m_glowColor = player->m_glowColor;
        state.m_maybeIsColliding = player->m_maybeIsColliding;
        state.m_jumpBuffered = player->m_jumpBuffered;
        state.m_stateRingJump = player->m_stateRingJump;
        state.m_wasJumpBuffered = player->m_wasJumpBuffered;
        state.m_wasRobotJump = player->m_wasRobotJump;
        state.m_stateJumpBuffered = player->m_stateJumpBuffered;
        state.m_stateRingJump2 = player->m_stateRingJump2;
        state.m_touchedRing = player->m_touchedRing;
        state.m_touchedCustomRing = player->m_touchedCustomRing;
        state.m_touchedGravityPortal = player->m_touchedGravityPortal;
        state.m_maybeTouchedBreakableBlock = player->m_maybeTouchedBreakableBlock;
        state.m_jumpRelatedAC2 = player->m_jumpRelatedAC2;
        state.m_touchedPad = player->m_touchedPad;
        state.m_yVelocity = player->m_yVelocity;
        state.m_fallSpeed = player->m_fallSpeed;
        state.m_isOnSlope = player->m_isOnSlope;
        state.m_wasOnSlope = player->m_wasOnSlope;
        state.m_slopeVelocity = player->m_slopeVelocity;
        state.m_maybeUpsideDownSlope = player->m_maybeUpsideDownSlope;
        state.m_isShip = player->m_isShip;
        state.m_isBird = player->m_isBird;
        state.m_isBall = player->m_isBall;
        state.m_isDart = player->m_isDart;
        state.m_isRobot = player->m_isRobot;
        state.m_isSpider = player->m_isSpider;
        state.m_isUpsideDown = player->m_isUpsideDown;
        state.m_isDead = player->m_isDead;
        state.m_isOnGround = player->m_isOnGround;
        state.m_isGoingLeft = player->m_isGoingLeft;
        state.m_isSideways = player->m_isSideways;
        state.m_isSwing = player->m_isSwing;
        state.m_reverseRelated = player->m_reverseRelated;
        state.m_maybeReverseSpeed = player->m_maybeReverseSpeed;
        state.m_maybeReverseAcceleration = player->m_maybeReverseAcceleration;
        state.m_xVelocityRelated2 = player->m_xVelocityRelated2;
        state.m_isDashing = player->m_isDashing;
        state.m_dashFireFrame = player->m_dashFireFrame;
        state.m_groundObjectMaterial = player->m_groundObjectMaterial;
        state.m_vehicleSize = player->m_vehicleSize;
        state.m_playerSpeed = player->m_playerSpeed;
        state.m_shipRotation = player->m_shipRotation;
        state.m_lastPortalPos = player->m_lastPortalPos;
        state.m_unkUnused3 = player->m_unkUnused3;
        state.m_isOnGround2 = player->m_isOnGround2;
        state.m_lastLandTime = player->m_lastLandTime;
        state.m_platformerVelocityRelated = player->m_platformerVelocityRelated;
        state.m_maybeIsBoosted = player->m_maybeIsBoosted;
        state.m_scaleXRelatedTime = player->m_scaleXRelatedTime;
        state.m_decreaseBoostSlide = player->m_decreaseBoostSlide;
        state.m_unkA29 = player->m_unkA29;
        state.m_isLocked = player->m_isLocked;
        state.m_controlsDisabled = player->m_controlsDisabled;
        state.m_lastGroundedPos = player->m_lastGroundedPos;
        

        state.m_lastActivatedPortal = player->m_lastActivatedPortal;
        state.m_hasEverJumped = player->m_hasEverJumped;
        state.m_hasEverHitRing = player->m_hasEverHitRing;
        state.m_playerColor1 = player->m_playerColor1;
        state.m_playerColor2 = player->m_playerColor2;
        state.m_position = player->m_position;
        state.m_rotation = player->getRotation();
        state.m_isSecondPlayer = player->m_isSecondPlayer;
        state.m_unkA99 = player->m_unkA99;
        state.m_totalTime = player->m_totalTime;
        state.m_isBeingSpawnedByDualPortal = player->m_isBeingSpawnedByDualPortal;
        state.m_audioScale = player->m_audioScale;
        state.m_unkAngle1 = player->m_unkAngle1;
        state.m_yVelocityRelated3 = player->m_yVelocityRelated3;
        state.m_defaultMiniIcon = player->m_defaultMiniIcon;
        state.m_swapColors = player->m_swapColors;
        state.m_switchDashFireColor = player->m_switchDashFireColor;
        state.m_followRelated = player->m_followRelated;
        state.m_unk838 = player->m_unk838;
        state.m_stateOnGround = player->m_stateOnGround;
        state.m_stateUnk = player->m_stateUnk;
        state.m_stateNoStickX = player->m_stateNoStickX;
        state.m_stateNoStickY = player->m_stateNoStickY;
        state.m_stateUnk2 = player->m_stateUnk2;
        state.m_stateBoostX = player->m_stateBoostX;
        state.m_stateBoostY = player->m_stateBoostY;
        state.m_maybeStateForce2 = player->m_maybeStateForce2;
        state.m_stateScale = player->m_stateScale;
        state.m_platformerXVelocity = player->m_platformerXVelocity;
        state.m_holdingRight = player->m_holdingRight;
        state.m_holdingLeft = player->m_holdingLeft;
        state.m_leftPressedFirst = player->m_leftPressedFirst;
        state.m_scaleXRelated = player->m_scaleXRelated;
        state.m_maybeHasStopped = player->m_maybeHasStopped;
        state.m_xVelocityRelated = player->m_xVelocityRelated;
        state.m_maybeGoingCorrectSlopeDirection = player->m_maybeGoingCorrectSlopeDirection;
        state.m_isSliding = player->m_isSliding;
        state.m_maybeSlopeForce = player->m_maybeSlopeForce;
        state.m_isOnIce = player->m_isOnIce;
        state.m_physDeltaRelated = player->m_physDeltaRelated;
        state.m_isOnGround4 = player->m_isOnGround4;
        state.m_maybeSlidingTime = player->m_maybeSlidingTime;
        state.m_maybeSlidingStartTime = player->m_maybeSlidingStartTime;
        state.m_changedDirectionsTime = player->m_changedDirectionsTime;
        state.m_slopeEndTime = player->m_slopeEndTime;
        state.m_isMoving = player->m_isMoving;
        state.m_platformerMovingLeft = player->m_platformerMovingLeft;
        state.m_platformerMovingRight = player->m_platformerMovingRight;
        state.m_isSlidingRight = player->m_isSlidingRight;
        state.m_maybeChangedDirectionAngle = player->m_maybeChangedDirectionAngle;
        state.m_unkUnused2 = player->m_unkUnused2;
        state.m_isPlatformer = player->m_isPlatformer;
        state.m_stateNoAutoJump = player->m_stateNoAutoJump;
        state.m_stateDartSlide = player->m_stateDartSlide;
        state.m_stateHitHead = player->m_stateHitHead;
        state.m_stateFlipGravity = player->m_stateFlipGravity;
        state.m_gravityMod = player->m_gravityMod;
        state.m_stateForce = player->m_stateForce;
        state.m_stateForceVector = player->m_stateForceVector;
        state.m_affectedByForces = player->m_affectedByForces;
        state.m_somethingPlayerSpeedTime = player->m_somethingPlayerSpeedTime;
        state.m_playerSpeedAC = player->m_playerSpeedAC;
        state.m_fixRobotJump = player->m_fixRobotJump;
        // state.m_holdingButtons = player->m_holdingButtons;
        state.m_inputsLocked = player->m_inputsLocked;
        state.m_gv0123 = player->m_gv0123;
        state.m_iconRequestID = player->m_iconRequestID;
        // state.m_robotBatchNode = player->m_robotBatchNode;
        // state.m_spiderBatchNode = player->m_spiderBatchNode;
        // state.m_unk958 = player->m_unk958;
        // state.m_robotFire = player->m_robotFire;
        state.m_unkUnused = player->m_unkUnused;
        // state.m_gameLayer = player->m_gameLayer;
        // state.m_parentLayer = player->m_parentLayer;
        // state.m_actionManager = player->m_actionManager;
        state.m_isOutOfBounds = player->m_isOutOfBounds;
        state.m_fallStartY = player->m_fallStartY;
        state.m_disablePlayerSqueeze = player->m_disablePlayerSqueeze;
        state.m_robotAnimation1Enabled = player->m_robotAnimation1Enabled;
        state.m_robotAnimation2Enabled = player->m_robotAnimation2Enabled;
        state.m_spiderAnimationEnabled = player->m_spiderAnimationEnabled;
        state.m_ignoreDamage = player->m_ignoreDamage;
        state.m_enable22Changes = player->m_enable22Changes;

        state.m_clickReleased = releasedClicks;

        // breaking, needs investigation

        // state.m_rotateObjectsRelated = player->m_rotateObjectsRelated;
        // state.m_potentialSlopeMap = player->m_potentialSlopeMap;
        // state.m_ringRelatedSet = player->m_ringRelatedSet;
        // for (int i = 0; i < player->m_touchingRings->count(); i++) {
        //     state.m_touchingRings.push_back(player->m_touchingRings->objectAtIndex(i));
        // }

        // state.m_touchedRings = player->m_touchedRings;
        // state.m_jumpPadRelated = player->m_jumpPadRelated;
        // state.m_playerFollowFloats = player->m_playerFollowFloats;
        // state.m_currentRobotAnimation = player->m_currentRobotAnimation;

        return state;
    }
    
    inline void apply(PlayerObject* player, const checkpoint_data& state, std::array<bool, 3>& releasedClicks, int64_t& currentFrame) {
        if (player == nullptr) return;

        currentFrame = state.currentFrame;
        
        // player->m_mainLayer = state.m_mainLayer;
        player->m_wasTeleported = state.m_wasTeleported;
        player->m_fixGravityBug = state.m_fixGravityBug;
        player->m_reverseSync = state.m_reverseSync;
        player->m_yVelocityBeforeSlope = state.m_yVelocityBeforeSlope;
        player->m_dashX = state.m_dashX;
        player->m_dashY = state.m_dashY;
        player->m_dashAngle = state.m_dashAngle;
        player->m_dashStartTime = state.m_dashStartTime;
        // player->m_dashRing = state.m_dashRing;
        player->m_slopeStartTime = state.m_slopeStartTime;
        player->m_justPlacedStreak = state.m_justPlacedStreak;
        // player->m_maybeLastGroundObject = state.m_maybeLastGroundObject;
        // player->m_collisionLogTop = state.m_collisionLogTop;
        // player->m_collisionLogBottom = state.m_collisionLogBottom;
        // player->m_collisionLogLeft = state.m_collisionLogLeft;
        // player->m_collisionLogRight = state.m_collisionLogRight;
        player->m_lastCollisionBottom = state.m_lastCollisionBottom;
        player->m_lastCollisionTop = state.m_lastCollisionTop;
        player->m_lastCollisionLeft = state.m_lastCollisionLeft;
        player->m_lastCollisionRight = state.m_lastCollisionRight;
        player->m_unk50C = state.m_unk50C;
        player->m_unk510 = state.m_unk510;
        player->m_currentSlope2 = state.m_currentSlope2;
        player->m_preLastGroundObject = state.m_preLastGroundObject;
        player->m_slopeAngle = state.m_slopeAngle;
        player->m_slopeSlidingMaybeRotated = state.m_slopeSlidingMaybeRotated;
        player->m_quickCheckpointMode = state.m_quickCheckpointMode;
        player->m_collidedObject = state.m_collidedObject;
        player->m_lastGroundObject = state.m_lastGroundObject;
        player->m_collidingWithLeft = state.m_collidingWithLeft;
        player->m_collidingWithRight = state.m_collidingWithRight;
        player->m_maybeSavedPlayerFrame = state.m_maybeSavedPlayerFrame;
        player->m_scaleXRelated2 = state.m_scaleXRelated2;
        player->m_groundYVelocity = state.m_groundYVelocity;
        player->m_yVelocityRelated = state.m_yVelocityRelated;
        player->m_scaleXRelated3 = state.m_scaleXRelated3;

        // #if defined(GEODE_IS_ANDROID) || defined(GEODE_IS_IOS)
        // player->m_collidingBetweenSteps = state.m_collidingBetweenSteps;
        // #endif

        player->m_scaleXRelated4 = state.m_scaleXRelated4;
        player->m_scaleXRelated5 = state.m_scaleXRelated5;
        player->m_isCollidingWithSlope = state.m_isCollidingWithSlope;
        // player->m_dashFireSprite = state.m_dashFireSprite;
        player->m_isBallRotating = state.m_isBallRotating;
        player->m_unk669 = state.m_unk669;
        player->m_currentPotentialSlope = state.m_currentPotentialSlope;
        player->m_currentSlope = state.m_currentSlope;
        player->unk_584 = state.unk_584;
        player->m_collidingWithSlopeId = state.m_collidingWithSlopeId;
        player->m_slopeFlipGravityRelated = state.m_slopeFlipGravityRelated;
        // player->m_particleSystems = state.m_particleSystems;
        player->m_slopeAngleRadians = state.m_slopeAngleRadians;
        player->m_rotationSpeed = state.m_rotationSpeed;
        player->m_rotateSpeed = state.m_rotateSpeed;
        player->m_isRotating = state.m_isRotating;
        player->m_isBallRotating2 = state.m_isBallRotating2;
        // player->m_hasGlow = state.m_hasGlow;
        player->m_isHidden = state.m_isHidden;
        // player->m_ghostType = state.m_ghostType;
        // player->m_ghostTrail = state.m_ghostTrail;
        // player->m_iconSprite = state.m_iconSprite;
        // player->m_iconSpriteSecondary = state.m_iconSpriteSecondary;
        // player->m_iconSpriteWhitener = state.m_iconSpriteWhitener;
        // player->m_iconGlow = state.m_iconGlow;
        // player->m_vehicleSprite = state.m_vehicleSprite;
        // player->m_vehicleSpriteSecondary = state.m_vehicleSpriteSecondary;
        // player->m_birdVehicle = state.m_birdVehicle;
        // player->m_vehicleSpriteWhitener = state.m_vehicleSpriteWhitener;
        // player->m_vehicleGlow = state.m_vehicleGlow;
        // player->m_swingFireMiddle = state.m_swingFireMiddle;
        // player->m_swingFireBottom = state.m_swingFireBottom;
        // player->m_swingFireTop = state.m_swingFireTop;
        // player->m_dashSpritesContainer = state.m_dashSpritesContainer;
        // player->m_regularTrail = state.m_regularTrail;
        // player->m_shipStreak = state.m_shipStreak;

        // player->m_waveTrail = state.m_waveTrail;
        if (player && player->m_waveTrail && player->m_waveTrail->m_pointArray) {
            auto points = player->m_waveTrail->m_pointArray;
            points->removeAllObjects();

            for (const auto& coord : state.m_waveTrailPoints) {
                auto newPointNode = PointNode::create(coord);
                
                if (newPointNode) {
                    points->addObject(newPointNode);
                }
            }
        }

        player->m_speedMultiplier = state.m_speedMultiplier;
        player->m_yStart = state.m_yStart;
        player->m_gravity = state.m_gravity;
        player->m_trailingParticleLife = state.m_trailingParticleLife;
        player->m_unk648 = state.m_unk648;
        player->m_gameModeChangedTime = state.m_gameModeChangedTime;
        player->m_padRingRelated = state.m_padRingRelated;
        player->m_maybeReducedEffects = state.m_maybeReducedEffects;
        player->m_maybeIsFalling = state.m_maybeIsFalling;
        player->m_shouldTryPlacingCheckpoint = state.m_shouldTryPlacingCheckpoint;
        player->m_playEffects = state.m_playEffects;
        player->m_maybeCanRunIntoBlocks = state.m_maybeCanRunIntoBlocks;
        player->m_hasGroundParticles = state.m_hasGroundParticles;
        player->m_hasShipParticles = state.m_hasShipParticles;
        player->m_isOnGround3 = state.m_isOnGround3;
        player->m_checkpointTimeout = state.m_checkpointTimeout;
        player->m_lastCheckpointTime = state.m_lastCheckpointTime;
        player->m_lastJumpTime = state.m_lastJumpTime;
        player->m_lastFlipTime = state.m_lastFlipTime;
        player->m_flashTime = state.m_flashTime;
        player->m_flashDuration = state.m_flashDuration;
        player->m_flashDelay = state.m_flashDelay;
        player->m_flashMainColor = state.m_flashMainColor;
        player->m_flashSecondColor = state.m_flashSecondColor;
        player->m_lastSpiderFlipTime = state.m_lastSpiderFlipTime;
        player->m_unkBool5 = state.m_unkBool5;
        player->m_maybeIsVehicleGlowing = state.m_maybeIsVehicleGlowing;
        // player->m_switchWaveTrailColor = state.m_switchWaveTrailColor;
        // player->m_practiceDeathEffect = state.m_practiceDeathEffect;
        player->m_accelerationOrSpeed = state.m_accelerationOrSpeed;
        player->m_snapDistance = state.m_snapDistance;
        player->m_ringJumpRelated = state.m_ringJumpRelated;

        player->m_objectSnappedTo = state.m_objectSnappedTo;
        // player->m_pendingCheckpoint = state.m_pendingCheckpoint;
        player->m_onFlyCheckpointTries = state.m_onFlyCheckpointTries;
        // player->m_robotSprite = state.m_robotSprite;
        // player->m_spiderSprite = state.m_spiderSprite;
        player->m_maybeSpriteRelated = state.m_maybeSpriteRelated;
        // player->m_playerGroundParticles = state.m_playerGroundParticles;
        // player->m_trailingParticles = state.m_trailingParticles;
        // player->m_shipClickParticles = state.m_shipClickParticles;
        // player->m_vehicleGroundParticles = state.m_vehicleGroundParticles;
        // player->m_ufoClickParticles = state.m_ufoClickParticles;
        // player->m_robotBurstParticles = state.m_robotBurstParticles;
        // player->m_dashParticles = state.m_dashParticles;
        // player->m_swingBurstParticles1 = state.m_swingBurstParticles1;
        // player->m_swingBurstParticles2 = state.m_swingBurstParticles2;
        player->m_useLandParticles0 = state.m_useLandParticles0;
        // player->m_landParticles0 = state.m_landParticles0;
        // player->m_landParticles1 = state.m_landParticles1;
        player->m_landParticlesAngle = state.m_landParticlesAngle;
        player->m_landParticleRelatedY = state.m_landParticleRelatedY;
        player->m_playerStreak = state.m_playerStreak;
        player->m_streakStrokeWidth = state.m_streakStrokeWidth;
        player->m_disableStreakTint = state.m_disableStreakTint;
        player->m_alwaysShowStreak = state.m_alwaysShowStreak;
        player->m_shipStreakType = state.m_shipStreakType;
        player->m_slopeRotation = state.m_slopeRotation;
        player->m_currentSlopeYVelocity = state.m_currentSlopeYVelocity;
        player->m_unk3d0 = state.m_unk3d0;
        player->m_blackOrbRelated = state.m_blackOrbRelated;
        player->m_unk3e0 = state.m_unk3e0;
        player->m_unk3e1 = state.m_unk3e1;
        player->m_isAccelerating = state.m_isAccelerating;
        player->m_isCurrentSlopeTop = state.m_isCurrentSlopeTop;
        player->m_collidedTopMinY = state.m_collidedTopMinY;
        player->m_collidedBottomMaxY = state.m_collidedBottomMaxY;
        player->m_collidedLeftMaxX = state.m_collidedLeftMaxX;
        player->m_collidedRightMinX = state.m_collidedRightMinX;
        player->m_fadeOutStreak = state.m_fadeOutStreak;
        player->m_canPlaceCheckpoint = state.m_canPlaceCheckpoint;
        player->m_originalMainColor = state.m_originalMainColor;
        player->m_originalSecondColor = state.m_originalSecondColor;
        // player->m_hasCustomGlowColor = state.m_hasCustomGlowColor;
        // player->m_glowColor = state.m_glowColor;
        player->m_maybeIsColliding = state.m_maybeIsColliding;
        player->m_jumpBuffered = state.m_jumpBuffered;
        player->m_stateRingJump = state.m_stateRingJump;
        player->m_wasJumpBuffered = state.m_wasJumpBuffered;
        player->m_wasRobotJump = state.m_wasRobotJump;
        player->m_stateJumpBuffered = state.m_stateJumpBuffered;
        player->m_stateRingJump2 = state.m_stateRingJump2;
        player->m_touchedRing = state.m_touchedRing;
        player->m_touchedCustomRing = state.m_touchedCustomRing;
        player->m_touchedGravityPortal = state.m_touchedGravityPortal;
        player->m_maybeTouchedBreakableBlock = state.m_maybeTouchedBreakableBlock;
        player->m_jumpRelatedAC2 = state.m_jumpRelatedAC2;
        player->m_touchedPad = state.m_touchedPad;
        player->m_yVelocity = state.m_yVelocity;
        player->m_fallSpeed = state.m_fallSpeed;
        player->m_isOnSlope = state.m_isOnSlope;
        player->m_wasOnSlope = state.m_wasOnSlope;
        player->m_slopeVelocity = state.m_slopeVelocity;
        player->m_maybeUpsideDownSlope = state.m_maybeUpsideDownSlope;
        player->m_isShip = state.m_isShip;
        player->m_isBird = state.m_isBird;
        player->m_isBall = state.m_isBall;
        player->m_isDart = state.m_isDart;
        player->m_isRobot = state.m_isRobot;
        player->m_isSpider = state.m_isSpider;
        player->m_isUpsideDown = state.m_isUpsideDown;
        player->m_isDead = state.m_isDead;
        player->m_isOnGround = state.m_isOnGround;
        player->m_isGoingLeft = state.m_isGoingLeft;
        player->m_isSideways = state.m_isSideways;
        player->m_isSwing = state.m_isSwing;
        player->m_reverseRelated = state.m_reverseRelated;
        player->m_maybeReverseSpeed = state.m_maybeReverseSpeed;
        player->m_maybeReverseAcceleration = state.m_maybeReverseAcceleration;
        player->m_xVelocityRelated2 = state.m_xVelocityRelated2;
        player->m_isDashing = state.m_isDashing;
        player->m_dashFireFrame = state.m_dashFireFrame;
        player->m_groundObjectMaterial = state.m_groundObjectMaterial;
        player->m_vehicleSize = state.m_vehicleSize;
        player->m_playerSpeed = state.m_playerSpeed;
        player->m_shipRotation = state.m_shipRotation;
        player->m_lastPortalPos = state.m_lastPortalPos;
        player->m_unkUnused3 = state.m_unkUnused3;
        player->m_isOnGround2 = state.m_isOnGround2;
        player->m_lastLandTime = state.m_lastLandTime;
        player->m_platformerVelocityRelated = state.m_platformerVelocityRelated;
        player->m_maybeIsBoosted = state.m_maybeIsBoosted;
        player->m_scaleXRelatedTime = state.m_scaleXRelatedTime;
        player->m_decreaseBoostSlide = state.m_decreaseBoostSlide;
        player->m_unkA29 = state.m_unkA29;
        player->m_isLocked = state.m_isLocked;
        player->m_controlsDisabled = state.m_controlsDisabled;
        player->m_lastGroundedPos = state.m_lastGroundedPos;
        player->m_lastActivatedPortal = state.m_lastActivatedPortal;
        player->m_hasEverJumped = state.m_hasEverJumped;
        player->m_hasEverHitRing = state.m_hasEverHitRing;
        player->m_playerColor1 = state.m_playerColor1;
        player->m_playerColor2 = state.m_playerColor2;
        player->m_position = state.m_position;
        player->setRotation(state.m_rotation);
        player->m_isSecondPlayer = state.m_isSecondPlayer;
        player->m_unkA99 = state.m_unkA99;
        player->m_totalTime = state.m_totalTime;
        player->m_isBeingSpawnedByDualPortal = state.m_isBeingSpawnedByDualPortal;
        player->m_audioScale = state.m_audioScale;
        player->m_unkAngle1 = state.m_unkAngle1;
        player->m_yVelocityRelated3 = state.m_yVelocityRelated3;
        player->m_defaultMiniIcon = state.m_defaultMiniIcon;
        player->m_swapColors = state.m_swapColors;
        player->m_switchDashFireColor = state.m_switchDashFireColor;
        player->m_followRelated = state.m_followRelated;
        player->m_unk838 = state.m_unk838;
        player->m_stateOnGround = state.m_stateOnGround;
        player->m_stateUnk = state.m_stateUnk;
        player->m_stateNoStickX = state.m_stateNoStickX;
        player->m_stateNoStickY = state.m_stateNoStickY;
        player->m_stateUnk2 = state.m_stateUnk2;
        player->m_stateBoostX = state.m_stateBoostX;
        player->m_stateBoostY = state.m_stateBoostY;
        player->m_maybeStateForce2 = state.m_maybeStateForce2;
        player->m_stateScale = state.m_stateScale;
        player->m_platformerXVelocity = state.m_platformerXVelocity;
        player->m_holdingRight = state.m_holdingRight;
        player->m_holdingLeft = state.m_holdingLeft;
        player->m_leftPressedFirst = state.m_leftPressedFirst;
        player->m_scaleXRelated = state.m_scaleXRelated;
        player->m_maybeHasStopped = state.m_maybeHasStopped;
        player->m_xVelocityRelated = state.m_xVelocityRelated;
        player->m_maybeGoingCorrectSlopeDirection = state.m_maybeGoingCorrectSlopeDirection;
        player->m_isSliding = state.m_isSliding;
        player->m_maybeSlopeForce = state.m_maybeSlopeForce;
        player->m_isOnIce = state.m_isOnIce;
        player->m_physDeltaRelated = state.m_physDeltaRelated;
        player->m_isOnGround4 = state.m_isOnGround4;
        player->m_maybeSlidingTime = state.m_maybeSlidingTime;
        player->m_maybeSlidingStartTime = state.m_maybeSlidingStartTime;
        player->m_changedDirectionsTime = state.m_changedDirectionsTime;
        player->m_slopeEndTime = state.m_slopeEndTime;
        player->m_isMoving = state.m_isMoving;
        player->m_platformerMovingLeft = state.m_platformerMovingLeft;
        player->m_platformerMovingRight = state.m_platformerMovingRight;
        player->m_isSlidingRight = state.m_isSlidingRight;
        player->m_maybeChangedDirectionAngle = state.m_maybeChangedDirectionAngle;
        player->m_unkUnused2 = state.m_unkUnused2;
        player->m_isPlatformer = state.m_isPlatformer;
        player->m_stateNoAutoJump = state.m_stateNoAutoJump;
        player->m_stateDartSlide = state.m_stateDartSlide;
        player->m_stateHitHead = state.m_stateHitHead;
        player->m_stateFlipGravity = state.m_stateFlipGravity;
        player->m_gravityMod = state.m_gravityMod;
        player->m_stateForce = state.m_stateForce;
        player->m_stateForceVector = state.m_stateForceVector;
        player->m_affectedByForces = state.m_affectedByForces;
        player->m_somethingPlayerSpeedTime = state.m_somethingPlayerSpeedTime;
        player->m_playerSpeedAC = state.m_playerSpeedAC;
        player->m_fixRobotJump = state.m_fixRobotJump;
        // player->m_holdingButtons = state.m_holdingButtons;
        player->m_inputsLocked = state.m_inputsLocked;
        player->m_gv0123 = state.m_gv0123;
        player->m_iconRequestID = state.m_iconRequestID;
        // player->m_robotBatchNode = state.m_robotBatchNode;
        // player->m_spiderBatchNode = state.m_spiderBatchNode;
        // player->m_unk958 = state.m_unk958;
        // player->m_robotFire = state.m_robotFire;
        player->m_unkUnused = state.m_unkUnused;
        // player->m_gameLayer = state.m_gameLayer;
        // player->m_parentLayer = state.m_parentLayer;
        // player->m_actionManager = state.m_actionManager;
        player->m_isOutOfBounds = state.m_isOutOfBounds;
        player->m_fallStartY = state.m_fallStartY;
        player->m_disablePlayerSqueeze = state.m_disablePlayerSqueeze;
        player->m_robotAnimation1Enabled = state.m_robotAnimation1Enabled;
        player->m_robotAnimation2Enabled = state.m_robotAnimation2Enabled;
        player->m_spiderAnimationEnabled = state.m_spiderAnimationEnabled;
        player->m_ignoreDamage = state.m_ignoreDamage;
        player->m_enable22Changes = state.m_enable22Changes;

        releasedClicks = state.m_clickReleased;

        // player->m_rotateObjectsRelated = state.m_rotateObjectsRelated;
        // player->m_potentialSlopeMap = state.m_potentialSlopeMap;
        // player->m_ringRelatedSet = state.m_ringRelatedSet;

        // player->m_touchingRings->removeAllObjects();
        // for (auto& ring : state.m_touchingRings) {
        //     player->m_touchingRings->addObject(ring);
        // }

        // player->m_touchedRings = state.m_touchedRings;
        // player->m_playerFollowFloats = state.m_playerFollowFloats;
        // player->m_jumpPadRelated = state.m_jumpPadRelated;
        // player->m_currentRobotAnimation = state.m_currentRobotAnimation;

    }

    inline void copyPlayerState(PlayerObject* from, PlayerObject* to) {
        if (!from || !to) return;

        to->m_wasTeleported = from->m_wasTeleported;
        to->m_fixGravityBug = from->m_fixGravityBug;
        to->m_reverseSync = from->m_reverseSync;

        to->m_yVelocityBeforeSlope = from->m_yVelocityBeforeSlope;
        to->m_dashX = from->m_dashX;
        to->m_dashY = from->m_dashY;
        to->m_dashAngle = from->m_dashAngle;
        to->m_dashStartTime = from->m_dashStartTime;
        to->m_slopeStartTime = from->m_slopeStartTime;
        to->m_justPlacedStreak = from->m_justPlacedStreak;

        to->m_lastCollisionBottom = from->m_lastCollisionBottom;
        to->m_lastCollisionTop = from->m_lastCollisionTop;
        to->m_lastCollisionLeft = from->m_lastCollisionLeft;
        to->m_lastCollisionRight = from->m_lastCollisionRight;
        to->m_unk50C = from->m_unk50C;
        to->m_unk510 = from->m_unk510;
        to->m_currentSlope2 = from->m_currentSlope2;
        to->m_preLastGroundObject = from->m_preLastGroundObject;
        to->m_slopeAngle = from->m_slopeAngle;
        to->m_slopeSlidingMaybeRotated = from->m_slopeSlidingMaybeRotated;
        to->m_quickCheckpointMode = from->m_quickCheckpointMode;
        to->m_collidedObject = from->m_collidedObject;
        to->m_lastGroundObject = from->m_lastGroundObject;
        to->m_collidingWithLeft = from->m_collidingWithLeft;
        to->m_collidingWithRight = from->m_collidingWithRight;
        to->m_maybeSavedPlayerFrame = from->m_maybeSavedPlayerFrame;
        to->m_scaleXRelated2 = from->m_scaleXRelated2;
        to->m_groundYVelocity = from->m_groundYVelocity;
        to->m_yVelocityRelated = from->m_yVelocityRelated;
        to->m_scaleXRelated3 = from->m_scaleXRelated3;

        to->m_scaleXRelated4 = from->m_scaleXRelated4;
        to->m_scaleXRelated5 = from->m_scaleXRelated5;
        to->m_isCollidingWithSlope = from->m_isCollidingWithSlope;
        to->m_isBallRotating = from->m_isBallRotating;
        to->m_unk669 = from->m_unk669;
        to->m_currentPotentialSlope = from->m_currentPotentialSlope;
        to->m_currentSlope = from->m_currentSlope;
        to->unk_584 = from->unk_584;
        to->m_collidingWithSlopeId = from->m_collidingWithSlopeId;
        to->m_slopeFlipGravityRelated = from->m_slopeFlipGravityRelated;
        to->m_slopeAngleRadians = from->m_slopeAngleRadians;
        to->m_rotationSpeed = from->m_rotationSpeed;
        to->m_rotateSpeed = from->m_rotateSpeed;
        to->m_isRotating = from->m_isRotating;
        to->m_isBallRotating2 = from->m_isBallRotating2;
        to->m_isHidden = from->m_isHidden;

        to->m_speedMultiplier = from->m_speedMultiplier;
        to->m_yStart = from->m_yStart;
        to->m_gravity = from->m_gravity;
        to->m_trailingParticleLife = from->m_trailingParticleLife;
        to->m_unk648 = from->m_unk648;
        to->m_gameModeChangedTime = from->m_gameModeChangedTime;
        to->m_padRingRelated = from->m_padRingRelated;
        to->m_maybeReducedEffects = from->m_maybeReducedEffects;
        to->m_maybeIsFalling = from->m_maybeIsFalling;
        to->m_shouldTryPlacingCheckpoint = from->m_shouldTryPlacingCheckpoint;
        to->m_playEffects = from->m_playEffects;
        to->m_maybeCanRunIntoBlocks = from->m_maybeCanRunIntoBlocks;
        to->m_hasGroundParticles = from->m_hasGroundParticles;
        to->m_hasShipParticles = from->m_hasShipParticles;
        to->m_isOnGround3 = from->m_isOnGround3;
        to->m_checkpointTimeout = from->m_checkpointTimeout;
        to->m_lastCheckpointTime = from->m_lastCheckpointTime;
        to->m_lastJumpTime = from->m_lastJumpTime;
        to->m_lastFlipTime = from->m_lastFlipTime;
        to->m_flashTime = from->m_flashTime;
        to->m_flashDuration = from->m_flashDuration;
        to->m_flashDelay = from->m_flashDelay;
        to->m_flashMainColor = from->m_flashMainColor;
        to->m_flashSecondColor = from->m_flashSecondColor;
        to->m_lastSpiderFlipTime = from->m_lastSpiderFlipTime;
        to->m_unkBool5 = from->m_unkBool5;
        to->m_maybeIsVehicleGlowing = from->m_maybeIsVehicleGlowing;
        // to->m_switchWaveTrailColor = from->m_switchWaveTrailColor;
        // to->m_practiceDeathEffect = from->m_practiceDeathEffect;
        to->m_accelerationOrSpeed = from->m_accelerationOrSpeed;
        to->m_snapDistance = from->m_snapDistance;
        to->m_ringJumpRelated = from->m_ringJumpRelated;
        to->m_objectSnappedTo = from->m_objectSnappedTo;
        to->m_onFlyCheckpointTries = from->m_onFlyCheckpointTries;
        to->m_maybeSpriteRelated = from->m_maybeSpriteRelated;

        to->m_useLandParticles0 = from->m_useLandParticles0;
        to->m_landParticlesAngle = from->m_landParticlesAngle;
        to->m_landParticleRelatedY = from->m_landParticleRelatedY;
        to->m_playerStreak = from->m_playerStreak;
        to->m_streakStrokeWidth = from->m_streakStrokeWidth;
        to->m_disableStreakTint = from->m_disableStreakTint;
        to->m_alwaysShowStreak = from->m_alwaysShowStreak;
        to->m_shipStreakType = from->m_shipStreakType;
        to->m_slopeRotation = from->m_slopeRotation;
        to->m_currentSlopeYVelocity = from->m_currentSlopeYVelocity;
        to->m_unk3d0 = from->m_unk3d0;
        to->m_blackOrbRelated = from->m_blackOrbRelated;
        to->m_unk3e0 = from->m_unk3e0;
        to->m_unk3e1 = from->m_unk3e1;
        to->m_isAccelerating = from->m_isAccelerating;
        to->m_isCurrentSlopeTop = from->m_isCurrentSlopeTop;
        to->m_collidedTopMinY = from->m_collidedTopMinY;
        to->m_collidedBottomMaxY = from->m_collidedBottomMaxY;
        to->m_collidedLeftMaxX = from->m_collidedLeftMaxX;
        to->m_collidedRightMinX = from->m_collidedRightMinX;
        to->m_fadeOutStreak = from->m_fadeOutStreak;
        to->m_canPlaceCheckpoint = from->m_canPlaceCheckpoint;
        to->m_originalMainColor = from->m_originalMainColor;
        to->m_originalSecondColor = from->m_originalSecondColor;
        to->m_maybeIsColliding = from->m_maybeIsColliding;

        to->m_jumpBuffered = from->m_jumpBuffered;
        to->m_stateRingJump = from->m_stateRingJump;
        to->m_wasJumpBuffered = from->m_wasJumpBuffered;
        to->m_wasRobotJump = from->m_wasRobotJump;
        to->m_stateJumpBuffered = from->m_stateJumpBuffered;
        to->m_stateRingJump2 = from->m_stateRingJump2;
        to->m_touchedRing = from->m_touchedRing;
        to->m_touchedCustomRing = from->m_touchedCustomRing;
        to->m_touchedGravityPortal = from->m_touchedGravityPortal;
        to->m_maybeTouchedBreakableBlock = from->m_maybeTouchedBreakableBlock;
        to->m_jumpRelatedAC2 = from->m_jumpRelatedAC2;
        to->m_touchedPad = from->m_touchedPad;

        to->m_yVelocity = from->m_yVelocity;
        to->m_fallSpeed = from->m_fallSpeed;
        to->m_isOnSlope = from->m_isOnSlope;
        to->m_wasOnSlope = from->m_wasOnSlope;
        to->m_slopeVelocity = from->m_slopeVelocity;
        to->m_maybeUpsideDownSlope = from->m_maybeUpsideDownSlope;
        to->m_isShip = from->m_isShip;
        to->m_isBird = from->m_isBird;
        to->m_isBall = from->m_isBall;
        to->m_isDart = from->m_isDart;
        to->m_isRobot = from->m_isRobot;
        to->m_isSpider = from->m_isSpider;
        to->m_isUpsideDown = from->m_isUpsideDown;
        to->m_isDead = from->m_isDead;
        to->m_isOnGround = from->m_isOnGround;
        to->m_isGoingLeft = from->m_isGoingLeft;
        to->m_isSideways = from->m_isSideways;
        to->m_isSwing = from->m_isSwing;

        to->m_reverseRelated = from->m_reverseRelated;
        to->m_maybeReverseSpeed = from->m_maybeReverseSpeed;
        to->m_maybeReverseAcceleration = from->m_maybeReverseAcceleration;
        to->m_xVelocityRelated2 = from->m_xVelocityRelated2;
        to->m_isDashing = from->m_isDashing;
        to->m_dashFireFrame = from->m_dashFireFrame;
        to->m_groundObjectMaterial = from->m_groundObjectMaterial;
        to->m_vehicleSize = from->m_vehicleSize;
        to->m_playerSpeed = from->m_playerSpeed;
        to->m_shipRotation = from->m_shipRotation;
        to->m_lastPortalPos = from->m_lastPortalPos;
        to->m_unkUnused3 = from->m_unkUnused3;
        to->m_isOnGround2 = from->m_isOnGround2;
        to->m_lastLandTime = from->m_lastLandTime;
        to->m_platformerVelocityRelated = from->m_platformerVelocityRelated;
        to->m_maybeIsBoosted = from->m_maybeIsBoosted;
        to->m_scaleXRelatedTime = from->m_scaleXRelatedTime;
        to->m_decreaseBoostSlide = from->m_decreaseBoostSlide;
        to->m_unkA29 = from->m_unkA29;
        to->m_isLocked = from->m_isLocked;
        to->m_controlsDisabled = from->m_controlsDisabled;
        to->m_lastGroundedPos = from->m_lastGroundedPos;

        to->m_lastActivatedPortal = from->m_lastActivatedPortal;
        to->m_hasEverJumped = from->m_hasEverJumped;
        to->m_hasEverHitRing = from->m_hasEverHitRing;
        to->m_playerColor1 = from->m_playerColor1;
        to->m_playerColor2 = from->m_playerColor2;
        
        to->m_position = from->m_position;
        to->setPosition(from->getPosition());
        to->setRotation(from->getRotation());

        to->m_isSecondPlayer = from->m_isSecondPlayer;
        to->m_unkA99 = from->m_unkA99;
        to->m_totalTime = from->m_totalTime;
        to->m_isBeingSpawnedByDualPortal = from->m_isBeingSpawnedByDualPortal;
        to->m_audioScale = from->m_audioScale;
        to->m_unkAngle1 = from->m_unkAngle1;
        to->m_yVelocityRelated3 = from->m_yVelocityRelated3;
        to->m_defaultMiniIcon = from->m_defaultMiniIcon;
        to->m_swapColors = from->m_swapColors;
        to->m_switchDashFireColor = from->m_switchDashFireColor;
        to->m_followRelated = from->m_followRelated;
        to->m_unk838 = from->m_unk838;

        to->m_stateOnGround = from->m_stateOnGround;
        to->m_stateUnk = from->m_stateUnk;
        to->m_stateNoStickX = from->m_stateNoStickX;
        to->m_stateNoStickY = from->m_stateNoStickY;
        to->m_stateUnk2 = from->m_stateUnk2;
        to->m_stateBoostX = from->m_stateBoostX;
        to->m_stateBoostY = from->m_stateBoostY;
        to->m_maybeStateForce2 = from->m_maybeStateForce2;
        to->m_stateScale = from->m_stateScale;
        to->m_platformerXVelocity = from->m_platformerXVelocity;
        to->m_holdingRight = from->m_holdingRight;
        to->m_holdingLeft = from->m_holdingLeft;
        to->m_leftPressedFirst = from->m_leftPressedFirst;
        to->m_scaleXRelated = from->m_scaleXRelated;
        to->m_maybeHasStopped = from->m_maybeHasStopped;
        to->m_xVelocityRelated = from->m_xVelocityRelated;
        to->m_maybeGoingCorrectSlopeDirection = from->m_maybeGoingCorrectSlopeDirection;
        to->m_isSliding = from->m_isSliding;
        to->m_maybeSlopeForce = from->m_maybeSlopeForce;
        to->m_isOnIce = from->m_isOnIce;
        to->m_physDeltaRelated = from->m_physDeltaRelated;
        to->m_isOnGround4 = from->m_isOnGround4;
        to->m_maybeSlidingTime = from->m_maybeSlidingTime;
        to->m_maybeSlidingStartTime = from->m_maybeSlidingStartTime;
        to->m_changedDirectionsTime = from->m_changedDirectionsTime;
        to->m_slopeEndTime = from->m_slopeEndTime;
        to->m_isMoving = from->m_isMoving;
        to->m_platformerMovingLeft = from->m_platformerMovingLeft;
        to->m_platformerMovingRight = from->m_platformerMovingRight;
        to->m_isSlidingRight = from->m_isSlidingRight;
        to->m_maybeChangedDirectionAngle = from->m_maybeChangedDirectionAngle;
        to->m_unkUnused2 = from->m_unkUnused2;
        to->m_isPlatformer = from->m_isPlatformer;

        to->m_stateNoAutoJump = from->m_stateNoAutoJump;
        to->m_stateDartSlide = from->m_stateDartSlide;
        to->m_stateHitHead = from->m_stateHitHead;
        to->m_stateFlipGravity = from->m_stateFlipGravity;
        to->m_gravityMod = from->m_gravityMod;
        to->m_stateForce = from->m_stateForce;
        to->m_stateForceVector = from->m_stateForceVector;
        to->m_affectedByForces = from->m_affectedByForces;
        to->m_somethingPlayerSpeedTime = from->m_somethingPlayerSpeedTime;
        to->m_playerSpeedAC = from->m_playerSpeedAC;
        to->m_fixRobotJump = from->m_fixRobotJump;
        to->m_inputsLocked = from->m_inputsLocked;
        to->m_gv0123 = from->m_gv0123;
        to->m_iconRequestID = from->m_iconRequestID;

        to->m_unkUnused = from->m_unkUnused;
        to->m_isOutOfBounds = from->m_isOutOfBounds;
        to->m_fallStartY = from->m_fallStartY;
        to->m_disablePlayerSqueeze = from->m_disablePlayerSqueeze;
        to->m_robotAnimation1Enabled = from->m_robotAnimation1Enabled;
        to->m_robotAnimation2Enabled = from->m_robotAnimation2Enabled;
        to->m_spiderAnimationEnabled = from->m_spiderAnimationEnabled;
        to->m_ignoreDamage = from->m_ignoreDamage;
        to->m_enable22Changes = from->m_enable22Changes;
    }
} }
